---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  project: devops-apps
  source:
    chart: external-dns
    helm:
      values: |
        rbac:
          create: true
        publishInternalServices: true
        replicas: 2
        metrics:
          enabled: true
        aws:
          credentials:
            accessKey: 172.20.17.156:secret/data/external-dns#ACCESSKEY
            secretKey: 172.20.17.156:secret/data/external-dns#SECRETKEY
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.3.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
