---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: prometheus
  project: devops-apps
  source:
    chart: prometheus
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 13.7.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubewatch
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewatch
  namespace: argocd
spec:
  destination:
    name: dev
    namespace: kubewatch
  project: devops-apps
  source:
    chart: kubewatch
    helm:
      values: |
        replicaCount: 2
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.2.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
