---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: apps/v1
kind: Application
metadata:
  name: redis
  namespace: redis
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/locked: "true"
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: 14.1.1
  values:
    auth:
      password: test
